---
title: "Individual Assignment"
description: |
  take a try
author:
  - name: Li Yumeng
    url: https://nicetry.netlify.app/
date: 07-11-2021
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 3
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r} 
packages = c('igraph', 'tidygraph', 'ggraph', 'visNetwork', 'lubridate', 'clock', 'tidyverse','dplyr', 'tidyr','raster','sf','sp','tmap', 'gifski','mapview','writexl')
for (p in packages){
  if(!require(p, character.only = T)){
    install.packages(p)
  }
  library(p,character.only = T)
}
```

```{r}
credit_card <- read.csv("data/cc_data.csv")
glimpse(credit_card)
```

```{r}
loyalty_card <- read.csv("data/loyalty_data.csv")
glimpse(loyalty_card)
```

```{r}
credit_card$timestamp <- date_time_parse(credit_card$timestamp,
                zone = "",
                format = "%m/%d/%Y %H:%M")
glimpse(credit_card)
```

```{r}
loyalty_card$timestamp <- date_time_parse(loyalty_card$timestamp,
                zone = "",
                format = "%m/%d/%Y")
glimpse(loyalty_card)
```


```{r}
credit_card$Date <- format(credit_card$timestamp, format = "%Y-%m-%d")
credit_card$Date <- date_time_parse(credit_card$Date, zone = "", format = "%Y-%m-%d")
glimpse(credit_card)
```

```{r}
card_joined <- credit_card %>%
  full_join(loyalty_card, by = c("Date" = "timestamp", "location", "price"))

```

```{r}
popular_credit_card <- credit_card %>%
  group_by(location) %>%
  summarise(count = n()) %>%
  arrange(desc(count))
```

```{r}
popular_loyalty_card <- loyalty_card %>%
  group_by(location) %>%
  summarise(count = n()) %>%
  arrange(desc(count))
  
```

```{r}
popular_locations <- card_joined %>%
  filter(location %in% c("Katerina's Cafe", "Hippokampos", "Guy's Gyros", "Brew've Been Served", "Ouzeri Elian", "Hallowed Grounds")) %>%
  drop_na(timestamp) %>%
  dplyr::select(-Date)
```

```{r}
abnormal_credit_card <- popular_locations %>%
  drop_na(loyaltynum) %>%
  group_by(last4ccnum) %>%
  summarize(loy_n = n_distinct(loyaltynum)) %>%
  filter(loy_n > 1)

```
    
```{r echo=TRUE, eval=TRUE}
packages = c('raster', 'sf', 
             'tmap', 'clock', 
             'tidyverse')
for (p in packages){
  if(!require(p, character.only = T)){
    install.packages(p)
  }
  library(p,character.only = T)
}
```

```{r}
bgmap <- raster("data/MC2-tourist.tif")
bgmap
```


```{r fig.height=5}
tmap_mode("plot")
tm_shape(bgmap) +
    tm_raster(bgmap,
              legend.show = FALSE)
```

```{r}
tm_shape(bgmap) +
    tm_rgb(bgmap,r=1,g=2,b=3,
           alpha = NA,
           saturation = 1,
           interpolate = TRUE,
           max.value = 255)
```

```{r}
Abila_st <- st_read(dsn = "data/Geospatial",
                    layer = "Abila")
```
```{r}
gps2 <- read_csv("data/gps2.csv")
glimpse(gps2)
```

```{r}
gps2$Timestamp <- date_time_parse(gps2$Timestamp,
                zone = "",
                format = "%m/%d/%Y %H:%M")
```

```{r}
gps2$id <- as_factor(gps2$id)
```

```{r}
gps_sf <- st_as_sf(gps2, 
                   coords = c("long", "lat"), 
                   crs= 4326)
```


```{r}
gps_sf$day <- format(gps_sf$Timestamp, format="%d")
gps_sf$hour <- format(gps_sf$Timestamp, format="%H")
gps_sf$minute <- format(gps_sf$Timestamp, format="%M")

```

```{r}
more_than_5mins <- gps_sf %>%
  filter(Seconds > 300)
```


```{r}
gps_path <- gps_sf %>%
  group_by(id, hour, day, minute) %>%
  summarize(m = mean(Timestamp), 
            do_union=FALSE) %>%
  st_cast("LINESTRING")
```

```{r}
p = npts(gps_path, by_feature = TRUE)
gps_path2 <- cbind(gps_path, p)
```

```{r}
gps_path2 <- gps_path2 %>%
  filter(p>1)
```

```{r echo=FALSE, eval=TRUE, fig.height=6}
gps_path_selected <- gps_path2 %>%
  filter(hour == "20", day == "07", id == 29)
tmap_mode("view")
tm_shape(bgmap) +
  tm_rgb(bgmap, r = 1,g = 2,b = 3,
       alpha = NA,
       saturation = 1,
       interpolate = TRUE,
       max.value = 255) +
  tm_shape(gps_path_selected) +
  tm_lines()
```

```{r}
gps_dot <- more_than_5mins %>%
  group_by(id, hour, day, minute) %>%
  summarize(geo_n = n_distinct(geometry)) %>%
  st_cast("POINT")
```
```{r}
card_selected <- card_joined %>%
  filter(last4ccnum == 9735)
```


```{r echo=FALSE, eval=TRUE, fig.height=6}
gps_dots_selected <- gps_dot %>%
  filter(day=='14', hour=='13', minute > '02')
tmap_mode("view")
tm_shape(bgmap) +
  tm_rgb(bgmap, r = 1,g = 2,b = 3,
       alpha = NA,
       saturation = 1,
       interpolate = TRUE,
       max.value = 255) +
  tm_shape(gps_dots_selected) +
  tm_dots()
```

```{r}
car <- read_csv("data/car-assignments.csv")
glimpse(car)

```
```{r}
car <- car %>%
  drop_na(CarID)

car$CarID <- as_factor(car$CarID)

glimpse(car)
glimpse(gps2)

```

```{r}
car_gps <- car %>%
  full_join(gps2, by = c("CarID" = "id"))

```

```{r}
car_gps <- st_as_sf(car_gps, 
                   coords = c("long", "lat"),
                       crs= 4326)

car_gps <- car_gps %>%
  unite("Name", FirstName, LastName, sep = " ")
```